language: python

services:
  - docker

before_install:
    - docker build -q -t rna_map -f docker/Dockerfile .

install:
  - pip install -r requirements.txt
  - pip install  .


script:
  - pytest
  - rna_map --docker -fa test/resources/case_1/test.fasta -fq1 test/resources/case_1/test_mate1.fastq -fq2 test/resources/case_1/test_mate2.fastq --dot_bracket test/resources/case_1/test.csv
  # make sure single reads work too
  - rna_map --docker -fa test/resources/case_1/test.fasta -fq1 test/resources/case_1/test_mate1.fastq

