language: python

services:
  - docker

before_install:
  - docker build -t dreem -f docker/dockerfile .

script:
  - python run_docker.py -fa test/test_1/test.fasta -fq1  test/test_1/test_mate1.fastq -fq2  test/test_1/test_mate2.fastq