name: Docker Linux Build

# Avoid running multiple jobs for the same branch
# in case of updates.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t rna-map -f docker/Dockerfile .

      - name: Install dependencies
        run: |
          pip install .

      - name: Run Docker test 1
        run: |
          rna-map -fa test/resources/case_1/test.fasta -fq1 test/resources/case_1/test_mate1.fastq --docker

      - name: Run Docker test 2
        run: |
          rna-map -fa test/resources/case_1/test.fasta -fq1 test/resources/case_1/test_mate1.fastq -fq2 test/resources/case_1/test_mate2.fastq --docker
      #- name: Check output files
      #  run: |
      #    if [[ -f output/BitVector_Files/mutation_histos.p ]]; then exit 1; fi

